### ISSUE TITLE
志愿者招募

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#16]

**Comment by AmazingAng** [comment]
贡献者: Erin
报名表： https://wj.qq.com/s2/11984152/7b17/
目前共招募到了14位小伙伴。文案+设计小伙伴1位，设计小伙伴1位，12位现场签到，还缺3位现场签到，1位文案，1-2位设计。

**Comment by hash-k-k** [comment]
@Erin1314 
今天进度：已经招募到9个小伙伴，新增3个 。
todo：明天优先 报名群、各个部门 ，后天 劣后 清华的人 or  推特上发一下。

**Comment by Erin1314** [comment]
截止3月29日，还差3位现场签到，1位文案，2位设计。

**Comment by AmazingAng** [comment]
现场志愿者还缺3-5人

**Comment by AmazingAng** [comment]
强制征兵: 4-7能来的贡献者都充当志愿者
