### ISSUE TITLE
Workshop/Speaker 安排

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#17]
目前 workshop 暂定4.6和4.7两个下午。
会参与的 Speaker：
1. Laura from Consensys
2. Frank from Chainlink
3. Scroll
4. Michael from TP
5. Leo from Starknet China
6. Microsoft
7. Tencent
8. Ray from Aspecta

**Comment by AmazingAng** [comment]
workshop speaker
1. 信息收集: 名字，email，twitter，organization, title, workshop title, time（会放在网站）
2. 拉个群
3. 发邀请函

**Comment by hash-k-k** [comment]
4.5号：晚上19:00，几个合办方发言、队长发言自我介绍2min、队员线上来听。地点待定。

workshop 固定在东升大厦会议室， 8场speaker +2 or 4 圆桌。
三个场地，需要有3~5个导师。
4.6号： 
4.7号：

4.8号 ：speaker 可以当评委（3~4个赛道，4~5个评委）

**Comment by Erin1314** [comment]
准备workshop发言人统计表，留kiwi tg/微信联系方式

肖臻，崔棉大师，0xaA，瑞国，那尔

**Comment by hash-k-k** [comment]
https://q6rsx4wom8.feishu.cn/docx/A58WdzHKFoH3hXx2JKicOYfFnld

**Comment by 0xhay** [comment]
#63
