### ISSUE TITLE
入选黑客松的开发者保证金

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#18]
为了保证入选的开发者能按时到场，ETH Beijing 将学习 ETH Global收取一定的保证金。4月5号黑客松第一天，24点前现场签到，就可以退还，否则没收。
学生收取 $50 或 350元；非学生收取 $100 或 700元

**Comment by AmazingAng** [comment]
截止: 3.26
链上: 24人
链下: 40人
1. 已经交的算成功报名，要拉个群。 @0xhay 
2. 今晚发个邮件通知。 0xAA

**Comment by hash-k-k** [comment]
正式群：人民币玩家 45人
数字资产：30人，没拉群
今晚继续社群、邮件通知

**Comment by 0xhay** [comment]
@0xhay 再拉一波

**Comment by AmazingAng** [comment]
基本完成，还需要做进一步核算。
后续： 4.5 号签到后退保证金。
