### ISSUE TITLE
ETH Beijing 周边设计与订制

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#19]

**Comment by AmazingAng** [comment]
T恤，袜子，帆布包今日确定版型。

**Comment by AmazingAng** [comment]
![651679724269_ pic_hd](https://user-images.githubusercontent.com/14728591/227778529-5e6cd10d-5c11-4d78-ad5c-e0d360877214.jpg)
![771679819485_ pic_
![801679819489_ pic_hd](https://user-images.githubusercontent.com/14728591/227778548-f91a2eba-1864-4992-acfe-255d4bd2daaa.jpg)
hd](https://user-images.githubusercontent.com/14728591/227778539-a57c9ef8-a003-4b05-b6ca-155039b842e9.jpg)
![781679819486_ pic_hd](https://user-images.githubusercontent.com/14728591/227778545-4c348e02-973a-4ad6-bc4d-8138d3493a55.jpg)

**Comment by AmazingAng** [comment]
衣服 2个版型各150件 （7天）
帆布包 2个版型各150件 （7天）
本子/笔，北大纪念品。
入场牌。
贴纸，还没开始设计。

**Comment by Erin1314** [comment]
T恤+帆布包 总价元

**Comment by 0xhay** [comment]
@haoyun 贴纸

**Comment by AmazingAng** [comment]
Erin 跟进
笔，本这两天在北大礼品店买好。
贴纸做好，找打印店打印。

**Comment by Erin1314** [comment]
贴纸4月1日出图，12款，A8 ,500张起订。

**Comment by hash-k-k** [comment]
贴纸订单 需要催促 @AmazingAng @Erin1314 
其他符合预期

**Comment by eeoeofl** [comment]
工牌设计和制作

**Comment by 0xhay** [comment]
工牌明天下单

**Comment by Erin1314** [comment]
收货人|快递公司|快递单号：刘佳良|顺丰速运|SF1690930694046,SF2041750737398,SF2041750737403,SF2041750737412,SF2041750737421,SF2041750737430。

T 恤/帆布包4月3日晚上发货啦，估计4月4日晚上到北京

**Comment by Erin1314** [comment]
4月4日下单贴纸，贴纸在figma上。
