### ISSUE TITLE
活动场地

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#21]
目前 ETH Beijing 有两个会场：
MetaSpace （50人） 24小时: 公共品赛道
东升大厦会议室 （80人） 早7到晚8：workshop + 开放研究赛道
联合印茶馆（50人）24小时：L2赛道

**Comment by AmazingAng** [comment]
阿斯顿发

**Comment by eeoeofl** [comment]
新增场地 清华金融学院南门 联合印学院茶
能够容纳50人左右，支持24小时

**Comment by Erin1314** [comment]
指引图优化

**Comment by Erin1314** [comment]
买哪些东西（餐食，丽华，提前几个小时去订）订固定的餐食。
准备矿泉水/泡面（先备个2-3箱，容易快速补货）。
插线板，京东订购，多余的未拆封退货。先订50款。多孔4-5个插头（电脑/手机）（3-5米）。
租睡袋/懒人沙发（备选）。

**Comment by eeoeofl** [comment]
场地参观完成
丽华快餐已给出菜单，提前一天确定第二天用餐数量即可

**Comment by 0xhay** [comment]
指引和志愿者需要分配好

**Comment by eeoeofl** [comment]
小米的插板 买了50只
多了可以不拆退货
