### ISSUE TITLE
学生住宿

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#22]
需要统计一下参与黑客松的学生需要住宿的情况。
时间：4月5-8号，共计4天

住宿：五道口附近的青旅，目前订了40人的床位。

**Comment by eeoeofl** [comment]
联系了两家青旅，能够提前5天预订，分别能预留20和10个床位
需要确定男生和女生数量 以确定如何分房

**Comment by AmazingAng** [comment]
@0xhay 今晚统计报名情况

**Comment by eeoeofl** [comment]
登巴客栈预计能腾出40个床位，其中女生床位大概有10个
剩下的可以安排在目田客栈
5-8号 3晚
价格会比携程价格低，具体价格要等确定人数后给

**Comment by 0xhay** [comment]
问卷已经统计一波，今晚会再发一次问卷（确定男女人数）

**Comment by Erin1314** [comment]
Leon deadline3月31日确定男女人数 @0xhay

**Comment by AmazingAng** [comment]
今天统计出来，目前的大概人数:
男: 60
女: 6

**Comment by eeoeofl** [comment]
以预定床位
5号-8号
男生：40人
女生：8人
9号
男生：38人
女生8人


目田客栈
女生：8（5号-9号）
男生：16（5号-9号）

登巴客栈
男生：24（5号-8号）
男生：22（9号）

**Comment by 0xhay** [comment]
结账并记录一下

**Comment by eeoeofl** [comment]
新增志愿者2男 2女住宿需求，正在联系客栈
