### ISSUE TITLE
每日推特宣发

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#23]
每日至少有两条 ETH Beijing Hackathon 的推特宣发。

**Comment by orrvan** [comment]
北京时间2023年4月5日，ETH Beijing Hackathon在北京五道口的 MetaSpace 正式启动。作为全球以太坊社区中备受瞩目的黑客马拉松之一，本次活动由 PKU Blockchain 和 WTF Academy 联合主办，ETHPlanet 和 Scroll 作为协办方，Scroll、Ethereum Foundation、Token Pocket、Mask、LD Capital、Cocos BCX 等公司作为赞助商，以及 Dorahacks、MetaSpace、ThubaDAO 等合作伙伴和支持社区的加入，共同致力于推动区块链技术和应用的创新发展。

本次比赛分为主赛道和赞助商赛道两个部分。主赛道要求参赛团队从三个赛道中选择一个，每个主赛道均有奖金 $10000，其中第一名 $5000，第二名 $3000，第三名 $2000。三个赛道分别是：公共品、Layer2 创新应用、开放研究 (非开发者向)。此外每个赞助商赛道有奖金 $2500，其中第一名 $1500，第二名 $1000。
除了奖金外，本次活动还将高校学生提供免费餐饮和住宿，并为非北京高校的学生提供旅行资助，报销50%的路费，封顶 $100。

ETH Beijing Hackathon 旨在促进以太坊生态系统在中国的发展，并为以太坊开发者提供一个展示自己才华和交流合作的平台。本次活动受到以太坊基金会的支持，参赛团队将在活动期间与其他开发者进行交流和合作，为推动区块链技术和产业的发展贡献自己的力量。

更多详情请看官网：
https://ethbeijing.xyz/
报名链接：https://docs.google.com/forms/d/e/1FAIpQLSe5qyxMneb3JULOdQhDCMvU7eEbnCGKTQ5G1uk1JKAwXC0IKw/viewform

**Comment by orrvan** [comment]
北京时间2023年4月5日，ETH Beijing Hackathon在北京五道口的MetaSpace正式启动。本次活动由PKU Blockchain和WTF Academy联合主办，ETHPlanet和Scroll为协办方，以及多家公司和合作伙伴的赞助和支持。
比赛分为主赛道和赞助商赛道两个部分。每个主赛道的奖金均为$10000，参赛团队需从三个赛道中选择一个。每个赞助商赛道奖金为$2500。
活动还为高校学生提供免费餐饮和住宿，为非北京高校学生提供路费补贴。
详细信息和报名链接请参考官网：
https://ethbeijing.xyz/


推文字数限制：
2023年4月5日，ETH Beijing Hackathon在北京五道口的MetaSpace正式启动。本次活动由PKU Blockchain和WTF Academy联合主办，ETHPlanet和Scroll为协办方。
本次活动奖金丰厚，还为高校学生提供免费餐饮和住宿，为非北京高校学生提供路费补贴。
详细信息和报名链接请参考官网：https://ethbeijing.xyz/

**Comment by 0xhay** [comment]
今日Update: chainlink
发嘉宾介绍、采访开发者（精选评论）

**Comment by AmazingAng** [comment]
今日 update: Scroll
待update: Consensys

**Comment by 0xhay** [comment]
Consensys, Galxe, Bixin to update

**Comment by Erin1314** [comment]
4月3日发布赞助商海报及pr稿件。
