### ISSUE TITLE
ETH Beijing Hackathon "白皮书"

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#24]
一个文档，详细介绍所有关于 ETH Beijing Hackathon 的信息。

**Comment by AmazingAng** [comment]
就用github repo中的中文版 
https://github.com/WTFAcademy/ETHBeijing/blob/main/README-cn.md
markdown教程: https://www.jianshu.com/p/ed47397774c4
@Erin1314

**Comment by 0xhay** [comment]
等日程、赞助商、以及评委嘉宾可加

**Comment by 0xhay** [comment]
Todo:
1. 参赛手册
2. 嘉宾手册
