### ISSUE TITLE
评委安排

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#25]
1. 黑客松队伍 4月6日和7日每晚 9 点提交当日的进展，供评委审查。
2. 8日下午3点所有队伍提交项目。3-6点所有评委一起评审出进入demo day的15个项目。

汇总表:
1. PKU Blockchain
2. WTF Academy
3. Scroll
4. ETH Planet
5. Metaspace
6. Token Pocket
7. Starkware
8. Consensys
9. Chainlink
10. Aspecta

**Comment by AmazingAng** [comment]
@hash-k-k

**Comment by AmazingAng** [comment]
统计完workshop speaker信息后，统计评委信息。

**Comment by AmazingAng** [comment]
4.6, 4.7 两天，每晚7点会有项目的进展报告，5分钟。
4.8，下午3点提交项目后，3-6点是集中评审阶段。

**Comment by AmazingAng** [comment]
评审标准，参考ETH Global黑客松的标准。

**Comment by Erin1314** [comment]
3月28日做完表格，3月29日确定

**Comment by 0xhay** [comment]
4月1号发通稿，需要在4.1之前确认好

**Comment by 0xhay** [comment]
#63
