### ISSUE TITLE
ETH Beijing贡献者回溯奖励 （已发放）

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#284]
ETH Beijing Hackathon圆满结束，现在我们需要统计每个贡献者的付出，并利用赞助剩余资金的一部分发放奖励。
### 统计范围
ETH Beijing Hackathon相关的一切贡献，包括网站开发/设计、外联、开发者运营、活动运营、物料准备、文案、现场志愿者等。
### 统计方法
以总贡献时长为准。
在这个帖子下面回复自己的贡献时长。可以参考下面的例子：
0xAA
1. 网站开发 (ethbeijing.xyz)
 - 项目管理: 5h
2. 外联
 - 联系以太坊基金会赞助: 5h
 - 联系其他赞助: 20h
 - 联系嘉宾: 10h
3. 开发者运营
 - 活动策划和宣传 60h
 - 筛选开发者 10h
4. 活动运营
 - 联系场地 10h
 - 联系住宿 5h
5. 现场志愿者
 - 现场志愿者: 30h
### 审核方法
各组负责人让组员尽快填写，先自己审核，最后所有负责人一起开会审核。
### 截止日期
4月18日24点

已发放: https://bscscan.com/tx/0x3490b026c87c5a5dbf9c61ff21c9c57801a1ec68b2849cac3fe711de9502fc20

**Comment by DEVINLIUPKU** [comment]
1. 海报设计
海报设计 4h
2. 现场志愿者
现场志愿者 8h （4.7下午东升）

总计：12h Devin

**Comment by fgambling** [comment]
赌徒

1. 活动运营
   联系住宿/场地 4h
3. 现场志愿者 35h
   (4.5 10: 00am - 10: 00pm)
   (4.7 12: 00pm - 10: 00pm)
   (4.8  8: 00am - 9: 00pm)

总计：39h

**Comment by xiaotongqiu2001** [comment]
Iris：

1. 现场志愿者
- 4.4 参与培训 4pm-6pm 2h
- 4.5 Metaspace 10am-10pm 12h
- 4.7 茶馆 8am-2pm 6h
- 4.8 Metaspace 2pm-9pm 7h

总计：27h

**Comment by Claudia1031** [comment]
Claudia：

网站开发 (ethbeijing.xyz)
Hero页面: 4h
赞助商logo部分: 4h
后续维护: 10h
外联
联系以太坊基金会赞助: 3h
联系xxx赞助: 5h
筹办After Party: 5h
统计参与嘉宾: 2h
开发者运营
收取保证金 3h
活动运营
培训志愿者 8h
联系场地 5h
联系住宿 5h
现场志愿者
现场志愿者: 30h
总计: 84h

**Comment by hubingliang** [comment]
网站开发 (ethbeijing.xyz)

b00l
 - FAQ页面3h
 - Footer页面 3h
 - 后续维护 1h

皮皮皮卡丘
 - Generous Prize 4h
 - Sponsors  4h
 - 后续维护 4h

饭否-彼得潘
 - Navbar  8h 
 - Hero  4h
 - 后续维护 4h

🌙
- init project 4h
- font 2h
- intro & Co-organization 4h
- Schedule 6h
- university && partner && media && venue 8h
- 多语言扩展和维护 6h
- 后期官网调整 6h

**Comment by CarrieY1** [comment]
Total:35h

- 设计宣传海报多版：12h
- 官网设计支持走查：5h
- 活动周边设计支持：2h
- 现场摄影摄像统筹：8h
- 嘉宾议程名册支持：2h
- Foresight space记录：2h
- 北大创新学社对接：2h
- ReadON合作沟通：1h
- 英国高校宣发沟通：1h

**Comment by Yanzzip** [comment]
Ray
制作宣传推送：5h

**Comment by orrvan** [comment]
卡壳：文案设计2h

**Comment by tankxu** [comment]
Tank Xu
- Hackthon 网站设计与交付：8h
- 动态 POAP 设计与导出 GIF：2.5h

**Comment by ElaineZhou528** [comment]
Elaine：
现场志愿者
4.4 参与培训 4pm-6pm 2h
4.5 Metaspace 10am-10pm 12h
4.7 Metaspace 2pm-10pm 8h
4.8 Metaspace 3pm-9pm 6h
总计：28h

**Comment by hash-k-k** [comment]
Kiwi ：

1.前期组织和早期黑客松方案：20h
外联方案：https://q6rsx4wom8.feishu.cn/docx/WJEadWN6poWbdax15XBc7DEQn9A
黑客松方案：https://q6rsx4wom8.feishu.cn/docx/Z2ahdNaLwontUyxRcRCcPfdWnAd

2.赞助外联：
2.1 Dorahacks的网站对接（四次会议）+日常群聊维护+赞助获取（1000u）：5h
2.2 Mask、LD Capital、cocosbcx赞助商跟进：5h
2.3 bixin资本赞助+赛道跟进确认：3h
2.4 其他赞助（华兴、水滴、Qiming、水滴 、 foresight 、 淡马锡、 zonff 、okx ventures、泰合 、锦秋 、mint ventures 、sky9、Hashkey、 y2z 、ant、 iosg、 dragonfly、 cobo 、火凤）：12h


3.中期宣传：
3.1 深潮space：12h
前期合作意向敲定：1h
嘉宾邀请：3h
主题内容确认：2h
海报制作：4h
推特宣传文案及宣发：1h
参与：2h

3.2 Foresight space：12h
前期合作意向敲定：1h
嘉宾邀请：3h
主题内容确认：2h
海报制作：4h
参与：2h

3.3 链捕手space：5h
前期合作意向敲定：1h
嘉宾邀请：1h
主题内容确认：1h
host：2h

3.4 其他space海报制作：4h

4.黑客松日程嘉宾邀请及表单统计：4h

5.After Party
5.1 拉赞助：4h
5.2 敲定合作细节，写赞助商务方案，和赞助商沟通：4h
5.3 海报设计，物料对接：4h

6.现场志愿者：10h

总计：107h

**Comment by Garvey-Wong** [comment]
Garvey （两周前发给Leon了，这里补上记录）
1. 外联

-  早期外联物料、ppt准备：6h
-  协助外联开会拉赞助和会后一些对接工作：5h
-  Dorahacks homepage创建和维护：3h

2. 开发者运营

-  创建团队、项目摸底问卷：3h
- 问卷表单数据整理（住宿信息、组队信息），排序、去重、统计、分表等：3h
- 队伍信息整理markdown文档，协助群内开发者维护信息等：3h

3. 现场志愿者

-  Metaspace 4.8 白天现场志愿者：7h

总计：30h

**Comment by Alinaa228** [comment]
Alina：

外联：
Foresight宣发合作：6h
Odaily宣发合作：6h
PAnews宣发合作：6h
链捕手宣发合作：6h
律动宣发合作：4h
深潮宣发合作：3h
巴比特宣发合作：2h
Tokendance沟通合作：2h

OAT活动内容策划：2h
Metaspace现场志愿者：3h
挑选现场照片，作为媒体素材：2h
撰写快讯文案：2h

总计：44h

**Comment by spn21** [comment]
厶月spn：

现场志愿者：
4.5 联合印茶馆 10am-10pm 12h
4.6 茶馆 10pm-6pm 8h
4.7 东升大厦9am-12am 3h
      茶馆12am-7pm  7h
总计： 30h

**Comment by where1235687** [comment]
Ken:
开发者运营：
开发者组队信息整理对接：5h
学生开发者信息收集整理对接：5h
开发者住宿信息整理对接：5h
筹备会议参会：6h
总计：21h

**Comment by huzhazha** [comment]
炸炸（孜成）：
现场志愿者
4.4 参与培训 4pm-6pm 2h
4.5  Meatspace 10am-12pm 14h 
4.6   Meatspace 0:00-8:00 8h
4.6    茶馆              14:00-17:00  3h
4.7   茶馆     2pm-12pm 10h
4.8   茶馆      0:00-18:00  18h
总计：55h

**Comment by where1235687** [comment]
您的邮件已收到，我将尽快给您回复，谢谢！                                                           王泓开

**Comment by Erin1314** [comment]
**文案支持：**

1.活动前宣通稿2.5h;
2.后宣通稿0.5h;

**志愿者招募支持+Demoday VC招募支持；**

1.制作志愿者报名表+Demoday VC报名表1h;

2.筛选时间充裕的志愿者，答疑指导志愿者上岗3h;

**现场活动支持：**
1.现场志愿者15h;
2.组织并主持高校区块链协会论坛3h.

**周边、海报支持：**
1.跟进T恤周边，从设计到制作3h;
2.跟进海报3h;

**赞助沟通支持：**
1.和太和资本、Basics Capital、Candaq、CertiK、Maverick沟通赞助事宜2h.

**总计：33h**

**Comment by where1235687** [comment]
您的邮件已收到，我将尽快给您回复，谢谢！                                                           王泓开
