### ISSUE TITLE
官网更新

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#30]
1. schedule： 活动组
2. speaker: 信息需要外联收集（姓名，头像，组织，推特）
3. venue: 信息需要活动组收集（图片，位置）
4. Bounty track: Scroll, Deploy smart contracts on Scroll. 1st: $1500, 2nd: $1000

**Comment by AmazingAng** [comment]
schedule更新 @hubingliang
需要更新的: venue （需要tank设计） 和 bounty track （复用 track）
活动方logo

**Comment by hubingliang** [comment]
venue 已更新 @hubingliang 
bounty track 已更新 @hubingliang

**Comment by 0xhay** [comment]
Todo: 更新partners

**Comment by hubingliang** [comment]
评委
speaker
支持高校？（更新待定）

**Comment by 0xhay** [comment]
今日更新：Galxe
Speaker、Mentor、Judge 收集物料

**Comment by hubingliang** [comment]
Partners 已更新 @hubingliang 
Speaker、Mentor、Judge 缺少物料
