### ISSUE TITLE
After Party

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#31]
4.8 日晚 9:30 开始。
可以用metaspace，也可以五道口包一个酒吧。
群体: 参与ETH Beijing的开发者和志愿者
拉单独的赞助。

Metaspace + 旁边还有一家酒吧

**Comment by hash-k-k** [comment]
3.27 进展：
1.权益和合作方沟通方式，@claudia
2.沟通了 共识实验室@kiwi
3.maverick沟通，想赞助主会场，仍在沟通@claudia
4.需要场地支持 ，谁能帮忙
5.物料支持 明确一下

**Comment by hash-k-k** [comment]
明天需要跟进 @hash-k-k  claudia

**Comment by Claudia1031** [comment]
酒会after party对外商务方案https://puffy-swim-913.notion.site/Eth-Beijing-After-party-BD-2f2e205dacb1471a9380e509686d3851
