### ISSUE TITLE
4.1大赛活动预发布

### ISSUE THREAD

**Issue by eeoeofl** [WTFAcademy/ETHBeijing#32]
目的：提前进行大赛预热，让赞助方和媒体有更多的曝光时间
参与人员：主办方，赞助方，媒体，各链协负责人
内容：
1、根据3.31截止报名情况，对外公布报名情况以及参赛院校
2、公布大赛各环节时间表
3、公布嘉宾和评委阵容

**Comment by eeoeofl** [comment]
线上发布 还是线下发布 ，主要看各部门时间
metaspace 4.1 （愚人节 周六）可以提前预留

**Comment by AmazingAng** [comment]
准备活动通稿 @Erin1314

**Comment by Erin1314** [comment]
需要嘉宾/评委资料，收集活动寄语，重磅嘉宾。

**Comment by 0xhay** [comment]
@AmazingAng 收集肖老师
需要做海报，4月1号之前，待定淘宝

**Comment by Erin1314** [comment]
deadline3月31日，收集完嘉宾/评委的照片等信息，做成海报/写进活动通稿内。

**Comment by AmazingAng** [comment]
今日收集好嘉宾/评委/导师的照片等信息，做成海报/写进活动通稿内。
