### ISSUE TITLE
线下物料

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#38]
1. 指示牌
2. 签到表
3. 宣传海报
4. 赞助商宣传物料

deadlin: 4.2日

**Comment by Erin1314** [comment]
3月31日大家再一起沟通是否 ok 赞助商带着他们的易拉宝过来。
支持官网上带logo的赞助商带易拉宝过来。

**Comment by AmazingAng** [comment]
赞助商可以带易拉宝，也可以不带。
海报小幽灵团队在帮忙做。

**Comment by 0xhay** [comment]
找一个志愿者负责物料，包括打印工牌，设计路线指引图，打印海报

**Comment by Erin1314** [comment]
![image](https://user-images.githubusercontent.com/85208028/229512791-ac82ddf3-2663-40c0-bbeb-a8c890b86b78.png)
指示牌 祈呓正在优化中，会在现有版本的基础上，添加上活动日程。

**Comment by Erin1314** [comment]
志愿者邵雪会支持工牌、海报、签到表的打印工作。

**Comment by Erin1314** [comment]
![image](https://user-images.githubusercontent.com/85208028/229514905-b338e607-9138-4967-a821-5dd9f926fe89.png)
现场指引物料设计稿，孵化器部分会写上几楼。
