### ISSUE TITLE
支持社区范围

### ISSUE THREAD

**Issue by hash-k-k** [WTFAcademy/ETHBeijing#43]
高校done
国内社区 如tokendance

**Comment by Erin1314** [comment]
1.Tokendance (已确认合作)
2.BlockChain Academy (已确认合作)
3.捕鲸船 
4.登链社区
5.Rebase
6.Builder DAO
7.Binary DAO:专注区块链优质项目投研 
8.Legal DAO 
万物岛:Web3华人创投社区基金，新一代共创、共治、共享的创投乌托邦
9.Tiger VC DAO:面向全球Web3投资者的去中心化VC品牌，致力于以DAO的方式让每个人都有机会参与Web 3一级市场投资。

大家可以评估下。我们去联系哪几家？比如对方帮我们在他们的社区内推推我们的2篇活动通稿（会前预发布稿件，会后活动情况获胜者稿件），提高我们活动的影响力。大家有啥希望支持社区支持的地方，也可补充哈

**Comment by 0xhay** [comment]
待定

**Comment by hash-k-k** [comment]
1.Tokendance (已确认合作)
2.捕鲸船
3.登链社区
4.Rebase
5.tintinland
