### ISSUE TITLE
财务统计

### ISSUE THREAD

**Issue by Erin1314** [WTFAcademy/ETHBeijing#49]
收入:  $63000
- ETH Foundation: $7000
- TP: $7000
- Cocos-BCX: $5000
- bixin: $10000
- Galxe: $5000
- Scaling x: $2000 (After Party)
- Future Money Fund: $2000 (After Party)
- Aspecta: $5000
- Scroll: $10000
- StarkWare: $5000
- LD Capital: $5000

目前团队已换了30000U（汇率 6.8），20.4 w rmb

支出: 169128.5 RMB + $38128 （共 $ 63000）
- 周边（T恤和帆布包……）28200 rmb，其中T恤 150*（52+56）=16200 rmb，帆布包 300*40=12000 rmb
- 杂项（插排，工牌手持打印机墨盒） 合计 4262
-青旅:   42000 rmb （70个开发者乘以50元/晚乘以四晚=70乘以150乘以4）
- 衣服快递: 1173 rmb
-旅行补助
非北京高校的学生的旅行补助，封顶是7000U

4月8号新增费用 合计36816元 （佳良）
- 餐费 5250
- 早饭 50份 单价15元 共计750
- 中饭80份 晚饭70份 单价30 共计4500
- after party 22600
- ai beer club 包场低消18000
- Metaspace 精酿 4600。瓶啤和软饮赠送
- 场地费 8000: 联和印茶馆场地费 2000/天*4
- 打印费用 486
- 工牌 270张 单价1 合计270
- 指示牌KT板 15/张 *8 合计120
- 免责书 320张 合计96
- PKU Blockchain / WTF Academy 易拉宝 480

购买云相册容量空间两次，合计598 rmb （Carri Yi）

学生 路费 住宿报销：50079.5 RMB (Haynar)

黑客松摄影费用: 4000 RMB

ETH Beijing HK午餐会：2000 RMB

5月11日 黑客松获胜团队奖金 $30000
txhash: https://etherscan.io/tx/0x0d4730ab34b1faac847a0ebbb87988712dd59e543520d95a99bd53e9d566ec89

6月1日 Scroll 赛道奖金: $2500 
txhash: https://etherscan.io/tx/0x37ba5bd67192f39c7fc882ca393dcf0e1ce3ba9388660ddcbd210707d5f79eb3

8月28日 ETH Beijing贡献者赏金 $2814  : https://bscscan.com/tx/0x3490b026c87c5a5dbf9c61ff21c9c57801a1ec68b2849cac3fe711de9502fc20

8月28日 PKU Blockchain经费  $2814

**Comment by b4thesunrise** [comment]
70 * 150 * 4 = 42000

**Comment by eeoeofl** [comment]
住宿目田17200 + 登巴 14100

明细
登巴150/天 22床位  4天
130床位 2个 3天

目田 180/天 24床位 4天

**Comment by eeoeofl** [comment]
住宿 2880
新增志愿者 2男2女床位
目田 180/天 4床位  4天

**Comment by eeoeofl** [comment]
采买周边 合计 4262

插排
小米6位+3USB 79.00*30个
小米8位 37.80*20个
工牌 26/包 *13包
手持打印机墨盒 399.00 *2

**Comment by eeoeofl** [comment]
餐费
5日 中餐50份 晚餐100份  单价30  共计4500
6日 早餐100份 单价15，中餐120份 晚餐120份  单价30  共计8700
矿泉水 6箱 单价 33.9  共计203.4
方便满 8箱 单价67.7  共计270.8

**Comment by eeoeofl** [comment]
4月8号新增费用 合计36336元
餐费 5250
早饭 50份 单价15元 共计750
中饭80份 晚饭70份 单价30 共计4500
after party 22600
ai beer club  包场低消18000
Metaspace  精酿 4600。瓶啤和软饮赠送

场地费 8000
联和印茶馆场地费 2000/天*4

打印费用 486
工牌 270张 单价1 合计270
指示牌KT板 15/张 *8  合计120
免责书 320张 合计96
ETHbeijing 泡沫板  费用metaspace出
ETHbeijing 海报KT板  费用metaspace出

**Comment by CarrieY1** [comment]
购买云相册容量空间两次，合计598rmb
-10GB 199rmb
-50GB 399rmb

**Comment by AmazingAng** [comment]
摄影 4000 rmb 已付

**Comment by AmazingAng** [comment]
ETH Beijing HK午餐会：
2000 RMB

**Comment by 0xhay** [comment]
学生 路费 住宿报销：
50079.5 RMB
