### ISSUE TITLE
促进组队

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/ETHBeijing#51]
收集各个项目信息，展示到github上，方便大家组队。

**Comment by AmazingAng** [comment]
运营组目前正在统计项目情况（队长提交），之后发布在github上，方便大家组队。
预计 4.1 完成

**Comment by 0xhay** [comment]
改成文字的，不要表格
Team Name, 要不要队员，项目介绍，需要技能，联系信息，一定要清晰明了

**Comment by AmazingAng** [comment]
## 1. GPAD Lab
- 简介: GPAD Protocol is a decentralized investment and financing agreement, users can freely create projects, invest, and realize post-investment programmable.
- 目标：完成Demo
- 是否招募队员: 否
- 如何联系: xxx

**Comment by Where12345687** [comment]
> 1. GPAD实验室
简介: GPAD Protocol是一个去中心化的投融资协议，用户可以自由创建项目，进行投资，实现投后可编程。
目标：完成Demo
是否招募队员: 否
如何联系：xxx
