### ISSUE TITLE
Demo Day 基金统计

### ISSUE THREAD

**Issue by 0xhay** [WTFAcademy/ETHBeijing#53]
4月8日晚上7-9点 @hash-k-k

**Comment by Erin1314** [comment]
选手在外候场。里面可以放开vc等机构观看demo day。
开放30-40个座位名额，欢迎晚来的机构朋友站着。

**Comment by AmazingAng** [comment]
@hash-k-k 做问卷，发给联系好的基金。
联系 10～20家，最后来10家左右。
