### ISSUE TITLE
PR需求和内容准备

### ISSUE THREAD

**Issue by hash-k-k** [WTFAcademy/ETHBeijing#57]
1.寄语@erin
2.报名结束宣发一下队伍
3.开幕仪式
4.workshop 多个
5.demoday
6.获奖项目
7.afterparty

**Comment by hash-k-k** [comment]
4.1&2  发第一个
4.3~4  发队伍的pr，多少人参加这种

**Comment by Erin1314** [comment]
活动预热通稿（未定稿版本） https://docs.google.com/document/d/162tuIQXAtdrpkWu6EbQSlbfuklYPcegJh0axH40Psus/edit#
