### ISSUE TITLE
Galxe OAT campaign

### ISSUE THREAD

**Issue by hash-k-k** [WTFAcademy/ETHBeijing#62]
1.开下Space，我们把后台权限给到你们 https://gal.xyz/dashboard-application

2.https://galxe.com/HBSclubs/campaign/GCb2jUUG6k 这个是我们之前跟Harvard Business school合作的OAT，他们是生成一个qr码放在现场让参与者连接钱包去领取
https://galxe.com/Odaily/campaign/GCb5MU4xou 这个是Odaily之前线下活动做的OAT，也是现场领取

3..活动目标：线上关注我们的赞助方的推特，转发我们的黑客松推特 就给oat

**Comment by Alinaa228** [comment]
4/2 联系设计制作OAT/ 已在Glaxe上创建初稿

**Comment by hash-k-k** [comment]
发布了 https://galxe.com/PKUBlockchain/campaign/GCpUrU1toQ
需要跟进宣传
