### ISSUE TITLE
 4.6~7 圆桌讨论选题

### ISSUE THREAD

**Issue by hash-k-k** [WTFAcademy/ETHBeijing#81]
- 以太坊上海升级带来的影响？

- 最近比起以太坊的L1生态，以OP，ARB为代表的的OPtimistic Rollup，以及以ZKSync，Scroll为代表的ZK Rollup持续火爆，如何看待这种现象？

- 扩容杀手锏Danksharding会是以太坊分片的未来吗？ Proto-Danksharding为什么是第一步？

- 生成式AI大热，我们应该抛弃Web3转向生成式AI吗？

- 作为Builder，在当下的大环境下，是要坚持初心，还是逆势Double Down，还是勒紧裤腰带过苦日子？

- 多链，跨链，全链，怎么看区块链的互操作性演进？

- ZK-EVM到底证明了什么？

**Comment by hash-k-k** [comment]
圆桌1-4.7  以太坊上海升级带来的影响？
1. Amazon Web Services Sr. Startup Advocate Great China Region,  0xUncleLee.Lalaland
2. 「Starknet 中文社区」核心贡献者 ，Leo Yang
3. Scroll Infra 工程师 , 时间的步伐 
4. Chainlink Developer advocate Frank Kong
5. Gitcoin Bob
6. LD Capital advisor  Jingyi

圆桌2-4.7  
1. ETHPlanet
2. 崔棉大师，捕鲸船
3. Sabrina Tan， Head of BD & Marketing，Aspecta
4. Lead Developer of NextID, Nyk Ma
5. Dorahacks ——待确认（可以不写）

**Comment by hash-k-k** [comment]
圆桌1-4.6 zk &layer2 by Scroll 
1. Kiwi， PKUBlockchain Vice President & OKX ventures researcher
2. Scroll 社区负责人  Young 
3. Bixin Ventures Partner，wangxi
4. Head of International Expansion, ConsenSys， Laura Shi
圆桌2-4.6 Public Goods 
1. 林川 ， PKUBlockchain Vice President & ABCDE Capital
2. 「Starknet 中文社区」核心贡献者 ，Leo Yang  
3. Cocobcx，Pano
4. 瑞国 
5. Starkscan ，Sean

**Comment by Erin1314** [comment]
deadline 4月4日晚上
